//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Qid { get; set; }
        public int Uid { get; set; }
        public int Mid { get; set; }
        public System.DateTime Qtime { get; set; }
        public string Qcontent { get; set; }
        public string Qanswer { get; set; }
        public int Qstate { get; set; }
    
        public virtual Mediciner Mediciner { get; set; }
        public virtual User User { get; set; }
    }
}
